- hosts: all

  vars:
    pip_install_packages:
      - name: docker
    timezone: America/New_York

  roles:
    - yatesr.timezone

  become: true

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
