- hosts: all

  vars:
    pip_install_packages:
      - name: docker
    timezone: America/New_York

  roles: {{ my_roles }}
    

  become: true

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
